apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: starbucks
  template:
    metadata:
      labels:
        app: starbucks
    spec:
      containers:
      - name: starbucks-container
        image: 706162601257.dkr.ecr.us-east-1.amazonaws.com/starbucks:6
        ports:
        - containerPort: 3000
